server:
  port: 9090
  name: api-gateway

spring:
  application:
    name: api-gateway
         
eureka:
  client:
    serviceUrl:
      defaultZone: http://container-eureka-server:8761/eureka
    instance:
      preferIpAddress: true